name: Blog Docker Image

on:
  push:
    paths:
      - "matrix/blog/package.json"
      - "matrix/blog/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image # 步骤名字
        run: |
          docker build ./matrix/blog --file ./matrix/blog/Dockerfile -t blog:latest #执行构建
          docker tag blog registry.cn-zhangjiakou.aliyuncs.com/rv/strapi_matrix:blog
          echo "${{ secrets.ALI_DOCKER_PWD }}" | docker login registry.cn-zhangjiakou.aliyuncs.com --username=${{ secrets.ALI_DOCKER_USER }} --password-stdin
          docker push registry.cn-zhangjiakou.aliyuncs.com/rv/strapi_matrix:blog # 推送
