name: Whoami

on:
  issue_comment:
    types: [created, deleted]
    
env:
  MBP_KEY: ${{ secrets.MBP_KEY }}
  MBP_PUB: ${{ secrets.MBP_PUB }}
  ECS_USER: ${{ secrets.ECS_USER }}
  ECS_HOST: ${{ secrets.ECS_HOST }}

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v1.3.0
        with:
          private-key: ${{ secrets.MBP_KEY }}
          public-key: ${{ secrets.MBP_PUB }}
      - name: SSH Commands
        run: |
          mkdir -p ~/.ssh
          cat ~/.ssh/id_rsa.pub
          ssh larry@calli.songlairui.cn:22 whoami
