name: Whoami

on:
  issue_comment:
    types: [created, deleted]

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          # Command to execute on the remote server.
          command: |
            docker pull registry-vpc.cn-zhangjiakou.aliyuncs.com/rv/strapi_matrix:blog
            docker images
          # Hostname or IP address of the server.
          host: ${{ secrets.ECS_HOST }}
          # Username for authentication.
          username: ${{ secrets.ECS_USER }}
          # Port number of the server.
          port: ${{ secrets.ECS_PORT }}
          # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          privateKey: ${{ secrets.MBP_KEY }}
          # Password for password-based user authentication.
          # password: ${{ secrets.ECS_PWD }}
          # For an encrypted private key, this is the passphrase used to decrypt it.
          # passphrase: # optional
          # Try keyboard-interactive user authentication if primary user authentication method fails.
          # tryKeyboard: # optional
