name: Whoami

on:
  issue_comment:
    types: [created, deleted]

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v1.3.0
        with:
          private-key: ${{ secrets.MBP_KEY }}
          public-key: ${{ secrets.MBP_PUB }}
      - name: SSH Commands
        run: |
          mkdir -p ~/.ssh
          cat ~/.ssh/id_rsa.pub
          ssh larry@39.98.210.208:22 whoami
