name: Whoami

on:
  issue_comment:
    types: [created, deleted]

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        run: |
          echo ${{ secrets.ECS_HOST }}
          echo ${{ secrets.ECS_USER }}
          echo ${{ secrets.ECS_PWD }}
          echo ${{ secrets.ECS_PORT }}
          echo
          whoami
          mkdir -p ~/.ssh
          ls ~/.ssh
