name: Whoami

on:
  issue_comment:
    types: [created, deleted]
    
env:
  MBP_KEY: ${{ secrets.MBP_KEY }}
  MBP_PUB: ${{ secrets.MBP_PUB }}
  ECS_USER: ${{ secrets.ECS_USER }}
  ECS_HOST: ${{ secrets.ECS_HOST }}

jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        run: |
          mkdir -p ~/.ssh
          echo $ECS_HOST
          echo ${ECS_USER}
          echo $MBP_KEY > ~/.ssh/id_rsa
          echo ${MBP_PUB} > ~/.ssh/id_rsa.pub
          cat ~/.ssh/id_rsa.pub
          ls -la ~/.ssh
          echo $ECS_USER $ECS_HOST
          ssh -l $ECS_USER $ECS_HOST whoami
